version: '3.8'

services:
  backend:
    build:
      context: ./fastq-upload-backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - /opt/fastq_storage:/app/storage

  frontend:
    build:
      context: ./fastq-upload-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
